name: CI

on:
  push:
    branches:
      - main
      - my_feature
  pull_request:
    branches:
      - main
      - my_feature

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Print environment variables (debug)
      run: |
        echo "DB_HOST: $DB_HOST"
        echo "DB_USER: $DB_USER"
        echo "DB_PASSWORD: $DB_PASSWORD"
        echo "DB_PORT: $DB_PORT"

    - name: Print env
      env:
        COVERAGE_RUN: true
      run: |
        echo "COVERAGE_RUN: $COVERAGE_RUN"
    - name: Generate coverage report
      run: |
        python -c "import os; print(os.getenv('MY_SECRET_KEY'))"  # 打印 MY_SECRET_KEY 环境变量值
        coverage run --parallel-mode -m unittest
        coverage combine
        coverage xml -i
      

    - name: Upload report to Codecov
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
