- name : Generate coverage report
  run:
    coverage run--source objprint--parallel-mode -m unittest
    coverage combine
    coverage xml-i
  env:
    COVERAGE RUN:True
- name:Upload reportto Codecov
  uses:codecov/codecov-action@v3
  with:
    file:./coverage.xml
