name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate coverage report
      run: |
        DB_HOST
        DB_USER
        DB_PASSWORD
        DB_PORT
        coverage run --parallel-mode -m unittest
        coverage combine
        coverage xml -i


    - name: Upload report to Codecov
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
